USE RMCDatabase;

insert into student (username, profileType, major, home_college, linkedin) values ('rodriguez.a24', 'Past Co-Op', 'Electrical Engineering', 'COE', 'https://www.linkedin.com/in/rodriguez-a/');
insert into student (username, profileType, major, home_college) values ('chen.m2025', 'Past Co-Op', 'Cybersecurity', 'Khoury');
insert into student (username, profileType, major, home_college, linkedin) values ('thompson.emma', 'Past Co-Op', 'Chemistry', 'COS', 'https://www.linkedin.com/in/thompson-emma/');
insert into student (username, profileType, major, home_college) values ('kim.s2024', 'Current Seeker', 'Biomedical Engineering', 'COE');
insert into student (username, profileType, major, home_college) values ('martinez.d25', 'Current Seeker', 'Business', 'D''Amore-McKim');
insert into student (username, profileType, major, home_college) values ('patel.r', 'Current Seeker', 'Data Science', 'Khoury');
insert into student (username, profileType, major, home_college) values ('williams.o2026', 'Current Seeker', 'English', 'CAMD');
insert into student (username, profileType, major, home_college, linkedin) values ('nguyen.liam', 'Past Co-Op', 'Biomedical Engineering', 'COE', 'https://www.linkedin.com/in/nguyen-liam/');
insert into student (username, profileType, major, home_college, linkedin) values ('baker.z23', 'Past Co-Op', 'Business', 'D''Amore-McKim', 'https://www.linkedin.com/in/baker-z/');
insert into student (username, profileType, major, home_college) values ('garcia.e', 'Current Seeker', 'Electrical Engineering', 'COE');
insert into student (username, profileType, major, home_college, linkedin) values ('jones.isabella', 'Past Co-Op', 'Electrical Engineering', 'COE', 'https://www.linkedin.com/in/jones-isabella/');
insert into student (username, profileType, major, home_college) values ('lee.n2025', 'Current Seeker', 'Electrical Engineering', 'COE');
insert into student (username, profileType, major, home_college, linkedin) values ('wilson.a', 'Past Co-Op', 'Media Arts', 'CAMD', 'https://www.linkedin.com/in/wilson-a/');
insert into student (username, profileType, major, home_college, linkedin) values ('brown.caleb', 'Past Co-Op', 'Neuroscience', 'COS', 'https://www.linkedin.com/in/brown-caleb/');
insert into student (username, profileType, major, home_college, linkedin) values ('taylor.j24', 'Past Co-Op', 'Psychology', 'Bouve', 'https://www.linkedin.com/in/taylor-j/');
insert into student (username, profileType, major, home_college, linkedin) values ('clark.m2023', 'Past Co-Op', 'Philosophy', 'COSSH', 'https://www.linkedin.com/in/clark-m/');
insert into student (username, profileType, major, home_college, linkedin) values ('moore.ben', 'Past Co-Op', 'Media Arts', 'CAMD', 'https://www.linkedin.com/in/moore-ben/');
insert into student (username, profileType, major, home_college, linkedin) values ('cooper.h', 'Past Co-Op', 'Biomedical Engineering', 'COE', 'https://www.linkedin.com/in/cooper-h/');
insert into student (username, profileType, major, home_college) values ('white.d2026', 'Current Seeker', 'Business', 'D''Amore-McKim');
insert into student (username, profileType, major, home_college, linkedin) values ('davis.lily', 'Past Co-Op', 'Data Science', 'Khoury', 'https://www.linkedin.com/in/davis-lily/');
insert into student (username, profileType, major, home_college) values ('miller.j', 'Current Seeker', 'Data Science', 'Khoury');
insert into student (username, profileType, major, home_college) values ('lopez.s2024', 'Current Seeker', 'Media Arts', 'CAMD');
insert into student (username, profileType, major, home_college) values ('scott.alex', 'Current Seeker', 'Philosophy', 'COSSH');
insert into student (username, profileType, major, home_college, linkedin) values ('hall.grace', 'Past Co-Op', 'Psychology', 'Bouve', 'https://www.linkedin.com/in/hall-grace/');
insert into student (username, profileType, major, home_college) values ('green.l2025', 'Current Seeker', 'Neuroscience', 'COS');
insert into student (username, profileType, major, home_college, linkedin) values ('king.emma', 'Past Co-Op', 'Journalism', 'CAMD', 'https://www.linkedin.com/in/king-emma/');
insert into student (username, profileType, major, home_college, linkedin) values ('adams.ryan', 'Past Co-Op', 'Cybersecurity', 'Khoury', 'https://www.linkedin.com/in/adams-ryan/');
insert into student (username, profileType, major, home_college, linkedin) values ('carter.o', 'Past Co-Op', 'Neuroscience', 'COS', 'https://www.linkedin.com/in/carter-o/');
insert into student (username, profileType, major, home_college) values ('turner.e2026', 'Current Seeker', 'Chemical Engineering', 'COE');
insert into student (username, profileType, major, home_college) values ('phillips.a', 'Current Seeker', 'Biomedical Engineering', 'COE');
insert into student (username, profileType, major, home_college) values ('rivera.sebastian', 'Current Seeker', 'Public Health', 'Bouve');
insert into student (username, profileType, major, home_college) values ('evans.m2025', 'Current Seeker', 'Nursing', 'Bouve');
insert into student (username, profileType, major, home_college, linkedin) values ('edwards.chris', 'Past Co-Op', 'Chemistry', 'COS', 'https://www.linkedin.com/in/edwards-chris/');
insert into student (username, profileType, major, home_college) values ('collins.n', 'Current Seeker', 'Media Arts', 'CAMD');
insert into student (username, profileType, major, home_college, linkedin) values ('sanders.w', 'Past Co-Op', 'Business', 'D''Amore-McKim', 'https://www.linkedin.com/in/sanders-w/');
